---
- hosts: app
  become: true

  tasks:
    - name: stoping tomcat
      service:
        name: tomcat
        state: stopped
        
    - name: remove webapps
      file:
        path: /opt/tomcat/webapps/*
        state: absent
        
    - name: copying webapp
      copy:
        src: target/raviLogin-1.0.war
        dest: /opt/tomcat/webapps/
        
    - name: started tomcat
      service:
        name: tomcat
        state: started
