---
- hosts: app
  become: true

  tasks:
    - name: stoping tomcat
      service:
        name: tomcat
        state: stopped
     - name: copying webapp
       copy:
         src: Readme.md
         dest: /opt/tomcat/webapps/
